# Giai đoạn 1: Build React App
FROM node:18-alpine as build-stage
WORKDIR /app

# --- SỬA Ở ĐÂY ---
COPY package.json ./
RUN npm install
# -----------------

COPY . .
RUN npm run build

# Giai đoạn 2: Chạy bằng Nginx
FROM nginx:alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]